apiVersion : apps/v1
kind: Deployment
metadata:
  name: "akshandonlabsjorsd-36b7"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "akshandonlabsjorsd-36b7"
  template:
    metadata:
      labels:
        app: "akshandonlabsjorsd-36b7"
    spec:
      containers:
        - name: "akshandonlabsjorsd-36b7"
          image: "acr82706845.azurecr.io/akshandonlabsjorsd"
          ports:
          - containerPort: 3000