apiVersion: v1
kind: Service
metadata:
    name: "akshandonlabsjorsd-36b7"
    labels:
        app: "akshandonlabsjorsd-36b7"
spec:
    type: LoadBalancer
    ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
    selector:
        app: "akshandonlabsjorsd-36b7"